language: cpp
sudo: false
compiler:
  - gcc
  - clang

# Cache .npm folder for faster npm install
cache:
  directories:
    - $HOME/.npm

git:
  depth: 999999

env:
  global:
    - GCC_VERSION="4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-4.8
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev

#Activate X Virtual Framebuffer to allow tests to
#use SFML.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
#Install newIDE tests dependencies
  - cd newIDE/app && npm install
  - cd ../..
#Install GDJS tests dependencies
  - cd GDJS/tests && npm install
  - cd ../..
#Get the correct version of gcc/g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
#Compile the tests only
  - mkdir .build-tests
  - cd .build-tests
  - cmake -DBUILD_GDJS=FALSE -DBUILD_IDE=FALSE -DBUILD_TESTS=TRUE -DNO_GUI=TRUE -DCMAKE_CXX_COMPILER=$(which $CXX) -DCMAKE_C_COMPILER=$(which $CC) ..
  - make -j 4
  - cd ..

script:
#GDCore and GDCpp game engine tests:
  - cd .build-tests
  - Core/GDCore_tests
  - GDCpp/GDCpp_tests
  - Extensions/PathfindingBehavior/PathfindingBehavior_Runtime_tests
  - Extensions/LinkedObjects/LinkedObjects_Runtime_tests
  - cd ..
#newIDE tests:
  - cd newIDE/app
  - npm test
  - npm run flow
  - npm run check-format
  - cd ../..
#GDJS game engine tests, disabled on Travis CI because ChromeHeadless can't be started.
#See them running on Semaphore-CI instead: https://semaphoreci.com/4ian/gd
#  - cd GDJS/tests && npm test
#  - cd ../..
